---
- name: Install Java 1.8 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python

- include: eap.yml

- name: Ensure that firewalld is installed
  yum: name=firewalld state=present

- name: Ensure that firewalld is started
  service: name=firewalld state=started

- name: deploy firewalld rules
  firewalld: immediate=yes port={{ item }} state=enabled permanent=yes
  with_items:
  - "{{ http_port }}/tcp"
  - "{{ https_port }}/tcp"

- include: apps.yml
  when: deploy_apps
